### ISSUE TITLE
Breaks with inherited types

### ISSUE THREAD

**Issue by makani** [timabell/ef-enum-to-lookup#18]
Throws "Error getting table name for entity type" when using default inheritance strategy in entity framework of table per hierarchy. So if you have a Bed class and Chair class both inherit from Furniture and EF stores the data for both in table named Furniture. It errors when looking for tables Bed and Chair.

**Comment by timabell** [comment]
Thanks for the info, I'll take a look. Can't promise when it'll be.

**Comment by timabell** [comment]
kaboom

	EfEnumToLookup.LookupGenerator.EnumGeneratorException was unhandled by user code
	  HResult=-2146233088
	  Message=Error getting table name for entity type 'Furniture'
	  Source=EfEnumToLookup
	  StackTrace:
	       at EfEnumToLookup.LookupGenerator.EnumToLookup.GetTableName(MetadataWorkspace metadata, EntityType entityType) in c:\repo\ef-enum-to-lookup\EfEnumToLookup\LookupGenerator\EnumToLookup.cs:line 298
	       at EfEnumToLookup.LookupGenerator.EnumToLookup.<>c__DisplayClass10.<FindReferences>b__c(<>f__AnonymousType0`2 <>h__TransparentIdentifier7) in c:\repo\ef-enum-to-lookup\EfEnumToLookup\LookupGenerator\EnumToLookup.cs:line 212
	       at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
	       at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
	       at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
	       at EfEnumToLookup.LookupGenerator.EnumToLookup.FindReferences(DbContext context) in c:\repo\ef-enum-to-lookup\EfEnumToLookup\LookupGenerator\EnumToLookup.cs:line 209
	       at EfEnumToLookup.LookupGenerator.EnumToLookup.Apply(DbContext context) in c:\repo\ef-enum-to-lookup\EfEnumToLookup\LookupGenerator\EnumToLookup.cs:line 73
	       at EFTests.Db.TestInitializer.Seed(MagicContext context) in c:\repo\ef-enum-to-lookup\EFTests\Db\TestInitializer.cs:line 17
	       at System.Data.Entity.DropCreateDatabaseAlways`1.InitializeDatabase(TContext context)
	       at System.Data.Entity.Internal.InternalContext.<>c__DisplayClassf`1.<CreateInitializationAction>b__e()
	       at System.Data.Entity.Internal.InternalContext.PerformInitializationAction(Action action)
	       at System.Data.Entity.Internal.InternalContext.PerformDatabaseInitialization()
	       at System.Data.Entity.Internal.LazyInternalContext.<InitializeDatabase>b__4(InternalContext c)
	       at System.Data.Entity.Internal.RetryAction`1.PerformAction(TInput input)
	  InnerException: EfEnumToLookup.LookupGenerator.EnumGeneratorException
	       HResult=-2146233088
	       Message=Multiple EntityTypeMappings found.
	       Source=EfEnumToLookup
	       StackTrace:
		    at EfEnumToLookup.LookupGenerator.EnumToLookup.GetTableName(MetadataWorkspace metadata, EntityType entityType) in c:\repo\ef-enum-to-lookup\EfEnumToLookup\LookupGenerator\EnumToLookup.cs:line 284
	       InnerException:

**Comment by timabell** [comment]
work in progress on branch inherited-types

**Comment by timabell** [comment]
fixed and merged into master

**Comment by timabell** [comment]
Released fix in v1.4.0, please report back with any problems. Thanks for your report.

**Comment by timabell** [comment]
ignore that ^
wrong issue #
